### ISSUE TITLE
Upgrade 8.5.5 to 8.6.3 failed. Blank pages

### ISSUE THREAD

**Issue by skidoo23** [bacula-web/bacula-web#140] opened 2022-11-18 15:27 UTC
**Describe the bug**
Bacula Web stopped working after upgrade from 8.5.5 to 8.6.3 only blank pages without html source displayed.

**To Reproduce**
Enter Bacula URL in Browser https://monitor.local:8080/bacula-web/index.php?page=test

`[Fri Nov 18 16:21:47.029960 2022] [php7:error] [pid 29541] [client 192.168.0.100:50715] PHP Fatal error:  Uncaught Error: Call to a member function assign() on null in /var/www/bacula-web/core/app/webapplication.class.php:233\nStack trace:\n#0 /var/www/bacula-web/core/app/webapplication.class.php(258): Core\\App\\WebApplication->init()\n#1 /var/www/bacula-web/public/index.php(27): Core\\App\\WebApplication->run()\n#2 {main}\n\nNext Error: Call to a member function send() on null in /var/www/bacula-web/core/app/webapplication.class.php:274\nStack trace:\n#0 /var/www/bacula-web/public/index.php(27): Core\\App\\WebApplication->run()\n#1 {main}\n  thrown in /var/www/bacula-web/core/app/webapplication.class.php on line 274`

```
# sudo -u www-data php bwc check
=====================
Checking requirements
=====================

        PHP version Ok (using 7.3.28-1+ubuntu16.04.1+deb.sury.org+1)
        PHP timezone Warning
        Protected assets folder is writable Ok
        Smarty cache folder write permission Ok

Checking installed PHP database extensions
==========================================

        mysql installed
        pgsql installed

Checking installed PHP extensions
=================================

        SQLite support Error
        Gettext support Ok
        Session support Ok
        PHP PDO support Ok
        PHP Posix support Ok

```
**Expected behavior**
View Bacula dashboard.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 64 bit
 - Browser Firefox ESR 64 bit
 - Version 102.5
 - PHP version [e.g. 7.3]

**Additional context**
Apache2 config

```
Alias /bacula-web /var/www/bacula-web/public
#        <Directory /var/www/bacula-web/> - before update
<Directory /var/www/bacula-web/public>
#               Options FollowSymLinks Multiviews - before update
#               AllowOverride None - before update
AllowOverride None
        </Directory>
```

Kindly asking for help.

**Comment by dfranco** [comment] 2022-11-18 16:59
Hi @skidoo23,

I'd be happy to help

Can you share the content of application/config/config.php please ?

Do not forget to remove/hide any sensitive information from it 

Looking forward for your feedback

**Comment by skidoo23** [comment] 2022-11-18 17:11
```
<?php

$config['show_inactive_clients'] = true;
$config['hide_empty_pools'] = false;
$config['datetime_format'] = 'd.m.Y H:i:s';
$config['enable_users_auth'] = false;
$config['debug'] = false;
$config['language'] = 'de_DE';
$config['rows_per_page'] = 25;

// PostgreSQL bacula catalog
$config[0]['label'] = 'DB Server';
$config[0]['host'] = 'database.local';
$config[0]['login'] = 'bacula';
$config[0]['password'] = 'XXX';
$config[0]['db_name'] = 'bacula';
$config[0]['db_type'] = 'pgsql';
$config[0]['db_port'] = '5432';
```

**Comment by dfranco** [comment] 2022-11-18 18:33
Look at this thread #129, it should fix it.

Please note PHP 7.3 will not be supported soon, and enable_user_auth option will be disappear too.
Future versions will force user authentication.

Hope it helps

**Comment by skidoo23** [comment] 2022-11-21 10:11
With `enable_user_auth = true;` setting Apache2 errorlog shows `52096] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: https://monitor.local:8080/bacula-web/index.php?page=test`

https://monitor.local:8080/bacula-web/index.php?page=test now shows

```
Database error Oops, looks like something went wrong :(
Details

A problem with the description below happen
Problem: could not find driver
```

Looks like I need on my old Ubuntu Xenial SQLite support for PHP which is AFAIK not available. Time to migrate to another machine.

BTW: does Bacula-Web really need integrated user authentication? On my current (old) machine Apache authenticates bacula-web pages against LDAP/AD

**Comment by dfranco** [comment] 2022-11-21 18:25
Please I have another question @skidoo23 

You mentioned LDAP/AD auth configured with Apache on your Ubuntu Xenial server.

Are you using OpenLDAP, Microsoft AD, something else ?

If you're using OpenLDAP, then if you can share which version you're using could be helpful to me as well.

Thanks for your feedback

**Comment by skidoo23** [comment] 2022-11-22 13:11
Thanks Davide for your support. Old version works fine for my purposes. I just thought I did something wrong.

OpenLDAP 2.4.42 (Xenial builtin) is currently in use. Access to Bacula-web pages is granted to members of the it group. Will downgrade to 8.5.5 Apache2 configuration

```
Alias /bacula-web /var/www/bacula-web/
<Directory /var/www/bacula-web>
                Options FollowSymLinks Multiviews
                AllowOverride None
                AuthName "Access to Bacula-Web"
                AuthType Basic
                AuthBasicProvider ldap
                AuthLDAPURL ldapi:///dc=customer,dc=local
                AuthLDAPGroupAttribute memberUid
                AuthLDAPGroupAttributeIsDN off
                Require ldap-group cn=it,ou=Groups,dc=customer,dc=local
</Directory>
```
 Migration to Samba 4.x or Microsoft Active Directory is planned for next year.

**Comment by dfranco** [comment] 2022-11-22 17:08
Thanks for your feedback @skidoo23 

Ok, by the time Bacula-Web offer LDAP user authentication, you can stick to version 8.5.5.

Would you be interested to test next major version before it's released ?

Just to make sure it does work in your environment.

Please let me know if this looks interesting for you.

**Comment by skidoo23** [comment] 2022-11-23 18:12
> Would you be interested to test next major version before it's released ?

Sure. I would like to help you (and of course the Bacula-Web project too).

**Comment by dfranco** [comment] 2022-11-24 02:57
> > Would you be interested to test next major version before it's released ?
> 
> 
> 
> Sure. I would like to help you (and of course the Bacula-Web project too).

Awesome ! I really appreciate.
I'll let you know once next major version is almost ready.

**Comment by dfranco** [comment] 2023-01-06 09:46
> > Would you be interested to test next major version before it's released ?
> 
> 
> 
> Sure. I would like to help you (and of course the Bacula-Web project too).

Hi @skidoo23 ,

As next release is almost ready to be published, Will you be able to make a test I publish it ?

**Comment by skidoo23** [comment] 2023-01-10 14:02
Maybe not this week. But next week it will be no problem.

**Comment by dfranco** [comment] 2023-01-10 15:15
> Maybe not this week. But next week it will be no problem.

Hi @skidoo23 ,

I'll release a minor feature release by the next few days.

But I'd still need your help testing the next major version anyway.

I'll keep you updated

**Comment by dfranco** [comment] 2023-01-16 06:40
> > Maybe not this week. But next week it will be no problem.
> 
> Hi @skidoo23 ,
> 
> I'll release a minor feature release by the next few days.
> 
> But I'd still need your help testing the next major version anyway.
> 
> I'll keep you updated

Hi @skidoo23,

I've made good progress but I'm still not ready to publish 8.7.0 minor feature release.
I'd need a couple of more days to make sure everything is tested and documented properly.

Will you be able to make some test on your side ?
Let me know the best way to share the details about testing it.

Thanks in advance for your feedback

**Comment by skidoo23** [comment] 2023-01-16 20:05
Please allow one or two days for testing. For testing details send me an email or branch project. Or both ;)

**Comment by dfranco** [comment] 2023-01-17 06:01
> Please allow one or two days for testing. For testing details send me an email or branch project. Or both ;)
> 
> 

@skidoo23 il create a thread in discussion once the "dev" version is stable and give you details to test it.

Thanks for contribution, I really appreciate community users help 😄

**Comment by dfranco** [comment] 2023-01-30 07:45
Hi @skidoo23 ,

Here's some update regarding this issue.

I've been a bit overwhelmed over the last few weeks, and the fixes I need to implement are quiet complex.
So a "testable" version of the dev branch will be available for you, but I'd need more time.

I have to tackle some other private things plus my job which is taking most of my time/energy.
Further than that, I'm preparing an IT certification which takes a lot of my time .

Sorry again about that, I hope I can get back to you later this week with the information you need to test next minor feature release before it's published

Thanks for your patience and comprehension.

**Comment by skidoo23** [comment] 2023-01-31 16:57
No problem. It's done, when it's done ;)

**Comment by dfranco** [comment] 2023-02-13 18:26
Hello @skidoo23 

I'm almost ready to releaase v8.7.0 with a good amount of fixes and more features.

If you have time to test, that would be awesome.

I'll instructions here later today.

**Comment by dfranco** [comment] 2023-02-13 18:41
Hi again @skidoo23 ,

Here's how to test the develop branch I'm working on

In a different folder, run this command (last parameter is up to you, choose whatever you want)

`composer create-project bacula-web/bacula-web:develop-dev test-bacula-web`

Move into the newly created folder
`cd test-bacula-web`

Copy your current configuration (config.php)
cp -pv /path/of/previous/config.php application/config/config.php

Make sure user authentication is disabled in your config.php file

`enable_user_auth = false;`

You're done on bacula-web side.

To finish the setup, you just need to modify your web server configuration to point to the new folder.
I would also make sure permissions are correct by following this [page](https://docs.bacula-web.org/en/latest/02_install/installcomposer.html#use-composer-to-install-bacula-web).

Thanks for your help

**Comment by skidoo23** [comment] 2023-02-15 02:06
Davide, I really appriciate your efforts. So I really hate to tell you there are still blank pages on my screen.

```
$ composer check
ext-dom        20031129    success
ext-gettext    7.4.33      success
ext-json       7.4.33      success
ext-libxml     7.4.33      success
ext-mbstring   7.4.33      success
ext-openssl    7.4.33      success
ext-pcre       7.4.33      success
ext-PDO        7.4.33      success
ext-Phar       7.4.33      success
ext-posix      7.4.33      success
ext-SimpleXML  7.4.33      success
ext-sqlite3    7.4.33      success
ext-tokenizer  7.4.33      success
ext-xml        7.4.33      success
ext-xmlwriter  7.4.33      success
php            7.4.33      success
```


Apache error log
```
[Wed Feb 15 02:45:05.310311 2023] [php:warn] [pid 30999] [client 2003:c5:2f1c:aa0b:3db9:42b3:3c54:b9f6:50728] PHP Warning:  Undefined array key "language" in /var/www/test-bacula-web/application/views/cache/5e598e9b124bff9b369bcbc6376dde3893d3db1d_0.file.footer.tpl.cache.php on line 63
[Wed Feb 15 02:45:05.310984 2023] [php:warn] [pid 30999] [client 2003:c5:2f1c:aa0b:3db9:42b3:3c54:b9f6:50728] PHP Warning:  Attempt to read property "value" on null in /var/www/test-bacula-web/application/views/cache/5e598e9b124bff9b369bcbc6376dde3893d3db1d_0.file.footer.tpl.cache.php on line 63
[Wed Feb 15 02:45:05.335647 2023] [php:error] [pid 30999] [client 2003:c5:2f1c:aa0b:3db9:42b3:3c54:b9f6:50728] PHP Fatal error:  Uncaught TypeError: Cannot assign array to property Core\\App\\WebApplication::$datetime_format_short of type string in /var/www/test-bacula-web/core/App/WebApplication.php:156\nStack trace:\n#0 /var/www/test-bacula-web/core/App/WebApplication.php(228): Core\\App\\WebApplication->bootstrap()\n#1 /var/www/test-bacula-web/public/index.php(35): Core\\App\\WebApplication->handle()\n#2 {main}\n  thrown in /var/www/test-bacula-web/core/App/WebApplication.php on line 156
```

**Comment by dfranco** [comment] 2023-02-15 05:50
Don't worry @skidoo23 , that was the purpose of you testing the dev branch before I release it.
So I make sure I haven't miss potential bugs, etc.

Let me try to reproduce it and I'll keep you updated.

**Comment by dfranco** [comment] 2023-02-15 05:51
Is this config still the one you're using ?

<?php

```
$config['show_inactive_clients'] = true;
$config['hide_empty_pools'] = false;
$config['datetime_format'] = 'd.m.Y H:i:s';
$config['enable_users_auth'] = false;
$config['debug'] = false;
$config['language'] = 'de_DE';
$config['rows_per_page'] = 25;

// PostgreSQL bacula catalog
$config[0]['label'] = 'DB Server';
$config[0]['host'] = 'database.local';
$config[0]['login'] = 'bacula';
$config[0]['password'] = 'XXX';
$config[0]['db_name'] = 'bacula';
$config[0]['db_type'] = 'pgsql';
$config[0]['db_port'] = '5432';
```

**Comment by skidoo23** [comment] 2023-02-15 15:41
No changes in configration - just `enable_user_auth = false;` as requested.

**Comment by dfranco** [comment] 2023-02-15 16:30
> No changes in configration - just `enable_user_auth = false;` as requested.

Does clearing your web browser cookies helps ?

**Comment by dfranco** [comment] 2023-02-15 16:52
> No changes in configration - just `enable_user_auth = false;` as requested.

I'd update the composer project too, as I've made some fixes since yesterday 

Hope it will help

**Comment by dfranco** [comment] 2023-02-16 05:52
alright @skidoo23 , I've found a couple of other small issues so
as I don't want to waste your time ... I'll reproduce the same setup you have, fix the small issues, and keep you updated when the dev branch is ready.

**Comment by skidoo23** [comment] 2023-02-16 11:37
Excellent. I'm looking forward to the improvements.

**Comment by dfranco** [comment] 2023-02-18 08:23
Hi @skidoo23 , develop branch is ready for testing

I'll make few more improvements + small fixes and release 8.7.0 by Monday morning.

Anyway, if you still face issues, I could release small fix release later.

Thanks for your help

**Comment by dfranco** [comment] 2023-02-19 15:19
> 
Hi @skidoo23,

Here's a quick update about your last issue, #154 has been created and the fix is already _in the oven._

**Comment by skidoo23** [comment] 2023-02-20 00:26
bacula-web develop from git. blank pages.

[Mon Feb 20 01:20:36.103757 2023] [php:warn] [pid 2598] [client 192.168.1.1:50808] PHP Warning:  require_once(/var/www/test-bacula-web/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/test-bacula-web/public/index.php on line 25
[Mon Feb 20 01:20:36.104418 2023] [php:error] [pid 2598] [client 192.168.1.1:50808] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/test-bacula-web/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/test-bacula-web/public/index.php:25\nStack trace:\n#0 {main}\n  thrown in /var/www/test-bacula-web/public/index.php on line 25

**Comment by dfranco** [comment] 2023-02-20 03:46
> bacula-web develop from git. blank pages.
> 
> 
> 
> [Mon Feb 20 01:20:36.103757 2023] [php:warn] [pid 2598] [client 192.168.1.1:50808] PHP Warning:  require_once(/var/www/test-bacula-web/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/test-bacula-web/public/index.php on line 25
> 
> [Mon Feb 20 01:20:36.104418 2023] [php:error] [pid 2598] [client 192.168.1.1:50808] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/test-bacula-web/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/test-bacula-web/public/index.php:25\nStack trace:\n#0 {main}\n  thrown in /var/www/test-bacula-web/public/index.php on line 25

from root path (not public)
$ composer install
$ composer dump-autoload 
$ composer check

Please paste output here

**Comment by skidoo23** [comment] 2023-02-21 01:24
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
> php bwc publishAssets
Publishing assets
$ composer dump-autoload
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
$ composer check
ext-dom        20031129    success
ext-gettext    7.4.33      success
ext-json       7.4.33      success
ext-libxml     7.4.33      success
ext-mbstring   7.4.33      success
ext-openssl    7.4.33      success
ext-pcre       7.4.33      success
ext-PDO        7.4.33      success
ext-Phar       7.4.33      success
ext-posix      7.4.33      success
ext-SimpleXML  7.4.33      success
ext-sqlite3    7.4.33      success
ext-tokenizer  7.4.33      success
ext-xml        7.4.33      success
ext-xmlwriter  7.4.33      success
php            7.4.33      success
```

bacula-web/index.php?page=test results in Apache2 error.log

```
[Tue Feb 21 02:17:31.669345 2023] [php:warn] [pid 1004] [client 192.168.0.100] PHP Warning:  Undefined array key "language" in /var/www/test-bacula-web/application/views/cache/5e598e9b124bff9b369bcbc6376dde3893d3db1d_0.file.footer.tpl.cache.php on line 63
[Tue Feb 21 02:17:31.669931 2023] [php:warn] [pid 1004] [client 192.168.0.100] PHP Warning:  Attempt to read property "value" on null in /var/www/test-bacula-web/application/views/cache/5e598e9b124bff9b369bcbc6376dde3893d3db1d_0.file.footer.tpl.cache.php on line 63
[Tue Feb 21 02:17:31.688588 2023] [php:error] [pid 1004] [client 192.168.0.100] PHP Fatal error:  Uncaught TypeError: Cannot assign array to property Core\\App\\WebApplication::$datetime_format_short of type string in /var/www/test-bacula-web/core/App/WebApplication.php:156\nStack trace:\n#0 /var/www/test-bacula-web/core/App/WebApplication.php(228): Core\\App\\WebApplication->bootstrap()\n#1 /var/www/test-bacula-web/public/index.php(35): Core\\App\\WebApplication->handle()\n#2 {main}\n  thrown in /var/www/test-bacula-web/core/App/WebApplication.php on line 156
```

**Comment by skidoo23** [comment] 2023-02-21 01:31
Commenting out `$config['datetime_format'] = 'd-m-Y H:i:s';` in config.php makes bacula-web working (in default language).

**Comment by dfranco** [comment] 2023-02-21 04:09
This bug has been fixed in #154 

If you have installed from source (git clone), please run again

`git pull`

**Comment by skidoo23** [comment] 2023-02-22 01:03
ok. first git clone, git checkout develop and composer install made bacula-web working. Thanks Davide, great work :)

**Comment by dfranco** [comment] 2023-02-22 02:55
> ok. first git clone, git checkout develop and composer install made bacula-web working. Thanks Davide, great work :)

That's a great news !

I have a couple of things to fix and will release v8.7.0

Thanks again to take the time to make these tests 👍

**Closed** 2023-02-22 04:14 UTC
Labels: question

**Comment by dfranco** [comment] 2024-02-26 19:40
Hi @skidoo23 ,
I'm currently working on next major release which will include LDAP authentication.
Would you be interested to discuss about the features you're looking for and make some tests on your side ?

**Comment by skidoo23** [comment] 2024-02-27 16:38
Sure. But production machines moved to Active Directory on Windows Server.

**Comment by dfranco** [comment] 2024-02-27 19:33
> Sure. But production machines moved to Active Directory on Windows Server.

It's even better as I don't have that kind in f environment to test.

Would like to discuss the details in #35, or in a different channel (email for instance) ?

**Comment by dfranco** [comment] 2024-02-28 17:09
> > Sure. But production machines moved to Active Directory on Windows Server.
> 
> It's even better as I don't have that kind of environment to test. I can test against OpenLDAP but not MS Active Directory.
> 
> Would like to discuss the details in #35, or in a different channel (email for instance) ?

@skidoo23 Any feedback ?

**Comment by skidoo23** [comment] 2024-02-28 23:09
I prefer https://github.com/bacula-web/bacula-web/issues/35 - maybe discussion is usefull for other people too.

Best regards.
