### ISSUE TITLE
SQL Error HY093 on first page load.

### ISSUE THREAD

**Issue by dandrzejewski** [bacula-web/bacula-web#97] opened 2021-12-07 15:41 UTC
**Describe the bug**
SQL Error HY093 on first page load.

**To Reproduce**
# Install and configure the application.
# Go to the initial page, index.php.

**Expected behavior**
The application should work correctly after configuration and not throw errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/181952/145059837-93be890b-f526-4780-9325-2ed7c804707d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Version 8.5.1
 - PHP version 8.0.13
 - MariaDB
 - Bacula Director 11.0.5

**Additional context**
This seems related to #93 and #94, but this is happening on MariaDB.

Here's a copy/paste of the error since you can't copy text from a screen shot:

<html><body>
<h4>Details</h4><p>A problem with the description below happen</p><b>Problem: </b>SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens<br><h4>Debug</h4><b>File: </b>/var/www/html/bacula-web/core/app/cmodel.class.php<br><b>Line: </b>138<br><b>Code: </b>HY093<br><h5>Exception trace</h5>

File: /var/www/html/bacula-web/core/app/cmodel.class.php on line 138 in function PDOStatement->execute
--
File: /var/www/html/bacula-web/application/models/jobs.model.php on line 104 in function CModel->run_query
File: /var/www/html/bacula-web/application/views/dashboard.view.php on line 94 in function Jobs_Model->count_Jobs
File: /var/www/html/bacula-web/core/app/webapplication.class.php on line 136 in function DashboardView->prepare
File: /var/www/html/bacula-web/index.php on line 21 in function WebApplication->run

</body>
</html>

**Comment by dandrzejewski** [comment] 2021-12-07 15:42
Happy to help troubleshoot as needed, let me know what you need.

**Comment by dfranco** [comment] 2021-12-07 20:44
Thanks @dandrzejewski for the bug report.

Which version of MariaDB are you using ?

**Comment by dfranco** [comment] 2021-12-09 10:13
Hi @dandrzejewski ,

I'll setup a Fedora 35 environment and try to reproduce this issue using packages provided by Fedora. I'll keep you posted.

**Comment by dandrzejewski** [comment] 2021-12-10 04:25
Sorry for the delay -

`[dave@mysql]~% mysql --version
mysql  Ver 15.1 Distrib 10.5.11-MariaDB, for Linux (x86_64) using  EditLine wrapper`

**Comment by dandrzejewski** [comment] 2021-12-10 04:25
My DB server is a separate machine and it's on Fedora 34.... thanks for the reminder to upgrade.

**Comment by dfranco** [comment] 2021-12-10 14:15
Thanks @dandrzejewski

**Comment by dfranco** [comment] 2021-12-14 05:55
Hello @dandrzejewski ,

I have prepared a clean Fedora 35 with bacula 11.0.5 using MariaDB catalog.

Unfortunately, I cannot reproduce the error you mention above :(

My guess is that you've installed Bacula-Web using Composer right ?

That's what I did and surprisingly, when I run this command 

`composer create-project --no-dev --prefer-dist bacula-web/bacula-web bacula-web`

I get Bacula-Web 8.4.4 installed, and not latest 8.5.1 which includes many PHP PDO fixes.

I'll investigate on that and let you know.

Best regards

**Comment by dfranco** [comment] 2021-12-15 04:06
@dandrzejewski 
I manage to get latest version installed by making sure php-mbstring is installed before, otherwise composer install 8.4.4 which doesn't contains this requirement yet.

**Comment by dfranco** [comment] 2021-12-15 05:11
@dandrzejewski 
I have a fix now, v8.5.2 will be released soon.

**Comment by dfranco** [comment] 2021-12-15 06:19
Fixed in #98 , thanks again for your bug report @dandrzejewski

**Closed by dfranco** 2021-12-15 06:19 UTC
Labels: bug
